dist: jammy
language: python

python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
  - "nightly"
install:
  - pip install -r requirements.txt
  - pip install .
script: pytest --cov=./openalias --cov=./bin tests.py
after_success:
  - codecov

